### PR TITLE
Adding Documentation

### PR DESCRIPTION
**Pull request by ilopezro**
Documentation Needed
====
- [x]  SystemUnitTest.pdf
- [x] WorkingProtoType.pdf
- [x] Installation guide/User manual

### CODE REVIEW

**Review by prateeknarayanan — APPROVED** [review]
Looks good to me

**Comment by dunchris** [comment]
From what I can tell, all docs are in.

**Review by dunchris — CHANGES_REQUESTED** [review]
Make sure the title of the page says Rideshare Price Comparer. I had changed it earlier, but it diverted from this branch, so I accidentally reset the change.

**Review by dunchris — APPROVED** [review]

**Review by Ernestohdz — APPROVED** [review]

**Review by dunchris — CHANGES_REQUESTED** [review]
I noticed that Sarah isn't a contributor to the project? She needs to be added

**Review by dunchris — APPROVED** [review]

**Comment by dunchris** [comment]
She's in the People section in contributors, but not visible in the Contributors section of Code.

**Comment by dunchris** [comment]
The auto deploy test: should that be skipped or not?

**Comment by ilopezro** [comment]
Yes -- autodeploy should be skipped because it's not in `main` yet. Contributors are based on PR merges. We can add her as a contributor is she opens up a PR and merges it in. What we could do is close down this PR and have her open up another pr with these same exact changes!

**Pull request merged**
